### PR TITLE
Implement a Backend

### PR DESCRIPTION
**Pull request by MujtabaMuhammad**
Creating a PR (i think)!

### CODE REVIEW

**Comment by salekinsirajus** [comment]
Where are the flask-related files? Like app.py, templates, etc?

**Comment by MujtabaMuhammad** [comment]
on the flask2 branch, see below:

[image: image.png]

**Comment by salekinsirajus** [comment]
*changes requested*
- remove the __pycache__ directory
- requirements.txt is empty, please add the contents in there.
- remove index.html and editor.html

**Comment by MujtabaMuhammad** [comment]
These tasks only need to be done on the local repo ?

**Comment by salekinsirajus** [comment]
One more change:
- Please move script.js from the root to static/js/script.js

**Comment by MujtabaMuhammad** [comment]
Check now, I believe this is all set

**Comment by salekinsirajus** [comment]
Awesome, looks good. merging now.

**Pull request merged**
